config/routes.rb
Rails.application.routes.draw do

  resources :labels, only: [:show]

  resources :advertisements, only: [:index, :show, :new, :create]
  resources :questions
  resources :topics do
    resources :posts, except: [:index]
  end

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
    resources :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]

  resources :welcome, only: [] do
    collection do
      get 'about'
      get 'contact'
      get 'faq'
    end
  end

  root to: 'welcome#index'

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show, :create, :update]
      resources :topics, except: [:edit, :new]
        resources :posts, only: [:create]
      resources :posts, only: [:update, :destroy, :show]
    end
  end

end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def show
    @question = Question.find(params[:id])
  end

  def create
    @question = Question.new
    @question.title = params[:question][:title]
    @question.body = params[:question][:body]
    @question.resolved = params[:question][:resolved]

    if @question.save
      flash[:notice] = "Question was saved"
      redirect_to @question
    else
      flash[:error] = "Ay Papi we have a problem"
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    @question.title = params[:question][:title]
    @question.body = params[:question][:body]
    @question.resolved = params[:question][:resolved]

    if @question.save
      flash[:notice] = "Question was saved"
      redirect_to @question
    else
      flash[:error] = "Ay Papi we have a problem"
      render :new
    end
  end

  def destroy
    @question = Question.find(params[:id])

    if @question.destroy
      flash[:notice] = "\"#{@question.title}\" was deleted successfully."
      redirect_to questions_path
    else
      flash[:error] = "There was an error deleting the post"
      render :show
    end
  end
end

app/views/questions/edit.haml
.container
  %h1.row Edit Question
  .row
    .col-md-4
      %h4 Guidelines for Questions
      %ul
        %li Make it topical
        %li Make it tropical
        %li Make sure it is targeted
    .col-md-8
      =form_for @question do |f|
        .form-group
          =f.label :title
          =f.text_field :title, class: 'form-control', placeholder: 'Title me'
        .form-group
          =f.label :body
          =f.text_area :body, rows: 8, class: 'form-control', placeholder: 'Enter post here'
        .form-group
          =f.label :resolved
          =f.check_box :resolved, class:"checkbox"
        .form-group
          =f.submit "Save", class: "btn btn-success"

app/views/questions/index.haml
.container
  - @questions.each do |question|
    %p
      = link_to question.title, question

app/views/questions/new.haml
.container
  %h1.col-sm-12 New Question
  = form_for @question do |f|
    .form-horizontal
      .form_group
        = f.label :title, class: "col-sm-2 control-label"
        .col-sm-10
          = f.text_field :title, class: "form-control", placeholder: "Fun title"
      .form_group
        = f.label :body, class: "col-sm-2 control-label"
        .col-sm-10
          = f.text_area :body, class: "form-control", placeholder: "1. Make it good."
      .form_group
        = f.label :resolved, class: "col-sm-2 control-label"
        .col-sm-10
          = f.check_box :resolved, class: "checkbox"
      .form_group
        .col-sm-offset-2.col-sm-10
          = f.submit "Save", class:"btn btn-success"

app/views/questions/show.haml
.container
  %h1.row=@question.title
  %p.row=@question.body
  - if @question.resolved
    %p.row <strong>Resolved</strong>
  - else
    %p.row <strong>Not Resolved</strong>
  .row
    =link_to "Edit", edit_question_path(@question), class: "btn btn-success"
    =link_to "Delete Question", @question, method: :delete, class: "btn btn-danger", data: {confirm: "Sure? Delete is forever"}