config/routes.rb
Rails.application.routes.draw do

  resources :labels, only: [:show]

  resources :advertisements, only: [:index, :show, :new, :create]
  resources :questions
  resources :topics do
    resources :posts, except: [:index]
  end

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
    resources :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]

  resources :welcome, only: [] do
    collection do
      get 'about'
      get 'contact'
      get 'faq'
    end
  end

  root to: 'welcome#index'

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show, :create, :update]
      resources :topics, except: [:edit, :new]
        resources :posts, only: [:create]
      resources :posts, only: [:update, :destroy, :show]
    end
  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :posts, dependent: :destroy

  has_many :labelings, as: :labelable
  has_many :labels, through: :labelings

  scope :privately_viewable, -> { where(public: false)}
  scope :publicly_viewable, -> { where(public: true)}
  scope :visible_to, -> (user) { user ? all : publicly_viewable }
end

app/controllers/api/v1/topics_controller.rb
class Api::V1::TopicsController < Api::V1::BaseController

  before_filter :authenticate_user, except: [:index, :show]
  before_filter :authorize_user, except: [:index, :show]

  def index
    topics = Topic.all
    render json: topics.to_json, status: 200
  end

  def show
    topic = Topic.find(params[:id])
    render json: topic.to_json(include: :posts), status: 200
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  before_action :require_sign_in, except: [:index, :show]
  before_action :authorize_user, except: [:index, :show]

  def index
    @topics = Topic.visible_to(current_user)
  end

  def show
    @topic = Topic.find(params[:id])

    unless @topic.public || current_user
      flash[:error] = "You must be signed in to view private topics"
      redirect_to new_session_path
    end
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)

    if @topic.save
      @topic.labels = Label.update_labels(params[:topic][:labels])
      flash[:notice] = "Topic was saved"
      redirect_to @topic
    else
      flash[:error] = "There was an error creating the topic. Please try again."
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])

    @topic.assign_attributes(topic_params)

    if @topic.save
      @topic.labels = Label.update_labels(params[:topic][:labels])
      flash[:notice] = "Post was updated"
      redirect_to @topic
    else
      flash[:error] = "There was an error saving your update. Try again."
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:id])

    if @topic.destroy
      flash[:notice] = "\"#{@topic.name}\" was deleted successfully."
      redirect_to action: :index
    else
      flash[:error] = "There was an error deleting the topic"
      render :show
    end
  end


  private
  def topic_params
    params.require(:topic).permit(:name, :description, :public)
  end

  def authorize_user
    unless current_user.admin?
      flash[:error] = "You must be an admin to do that"
      redirect_to topics_path
    end
  end

end

app/helpers/topics_helper.rb
module TopicsHelper

  def user_is_authorized_for_topics?
    current_user && current_user.admin?
  end

  def user_is_authorized_for_editing_topics?
    #current_user && (current_user.admin? || current_user.moderator?)
    current_user.moderator?
  end
end

app/views/topics/_form.haml
=form_for [topic] do |f|
  - if topic.errors.any?
    .alert.alert-danger
      %h4=pluralize(topic.errors.count, "error")
      %ul
        -topic.errors.full_messages.each do |msg|
          %li=msg
  = form_group_tag(topic.errors[:name]) do
    =f.label :name
    =f.text_field :name, class: 'form-control', placeholder: 'Enter a topic'
  = form_group_tag(topic.errors[:description]) do
    =f.label :description
    =f.text_area :description, class: 'form-control', placeholder: 'Enter a description'
  .form-group
    =f.label :public, class:'checkbox' do
      .row
        .col-sm-1
        .col-sm-1
          =f.check_box :public
        .col-sm-6
          %p Public Topic
  .form-group
    =f.submit "Save", class: 'btn btn-success'

app/views/topics/_topic.html.erb
<div class="media">
  <div class="media-body">
    <h4 class="media-heading">
      <%= link_to topic.name, topic %>
      <small><%= topic.description%></small>
    </h4>
  </div>
</div>

app/views/topics/edit.haml
.container
  %h1 Edit Topic
  .row
    .col-sm-4
      %p Guidelines for topics
      %ul
        %li No cats
        %li No cat pictures
        %li Keep it topical
        %li Cats are bad
    .col-sm-8
      =form_for @topic do |f|
        .form-group
          =f.label :name
          =f.text_field :name, class: 'form-control', placeholder: 'Your topic here'
        .form-group
          =f.label :description
          =f.text_area :description, rows: 8, class: 'form-control', placeholder: 'Your topic description here'
        .form-group
          =render partial: 'labels/form', locals: { f: f, labels: @topic.labels }
        .form-group
          =render partial: 'ratings/form', locals: { f: f, rating: @topic.rating }
        .form-group
          =f.label :public, class:'checkbox' do
            .row
              .col-sm-1
              .col-sm-1
                =f.check_box :public
              .col-sm-6
                %p Public Topic
        .form-group
          =f.submit "Save", class: 'btn btn-success'

app/views/topics/index.haml
.container
  %h1 Topics
  .row
    .col-md-8
      =render @topics
    - if user_is_authorized_for_topics?
      .col-md-4
        = link_to "New Topic", new_topic_path, class: "btn btn-success"

app/views/topics/new.haml
.container
  %h1 New Topic
  .row
    .col-sm-4
      %p Guidelines for topics
      %ul
        %li No cats
        %li No cat pictures
        %li Keep it topical
        %li Cats are bad
    .col-sm-8
      =form_for @topic do |f|
        .form-group
          =f.label :name
          =f.text_field :name, class: 'form-control', placeholder: 'Your topic name'
        .form-group
          =f.label :description
          =f.text_area :description, rows: 8, class: 'form-control', placeholder: 'Your topic description'
        .form-group
          =render partial: 'labels/form', locals: { f: f, labels: @topic.labels }
        .form-group
          =render partial: 'ratings/form', locals: { f: f, rating: @topic.rating } 
        .form-group
          =f.label :public, class: 'checkbox' do
            .row
              .col-sm-1
              .col-sm-1
                =f.check_box :public
              .col-sm-6
                %p Public Topic
        .form-group
          =f.submit "Save", class: 'btn btn-success'

app/views/topics/show.haml
.container
  %h1=@topic.name
  - if user_is_authorized_for_topics?
    = link_to "Edit Topic", edit_topic_path, class: 'btn btn-success'
    = link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-success'
  .row
    .col-md-8
      %p.lead
        = render partial: "labels/list", locals: { labels: @topic.labels }
        %br/
        = @topic.description
      - @topic.posts.each do |post|
        .media
          .media-body
            =render partial: 'votes/voter', locals: { post: post }
            %h4.media-heading
              =link_to post.title, topic_post_path(@topic, post)
            .small
              Submitted #{time_ago_in_words(post.created_at)} ago by #{post.user.name}
              %br/
              #{post.comments.count} Comments
    - if current_user
      .col-md-4
        =link_to "New Post", new_topic_post_path(@topic), class: 'btn btn-success'