config/routes.rb
Rails.application.routes.draw do

  resources :labels, only: [:show]

  resources :advertisements, only: [:index, :show, :new, :create]
  resources :questions
  resources :topics do
    resources :posts, except: [:index]
  end

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
    resources :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]

  resources :welcome, only: [] do
    collection do
      get 'about'
      get 'contact'
      get 'faq'
    end
  end

  root to: 'welcome#index'

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show, :create, :update]
      resources :topics, except: [:edit, :new]
        resources :posts, only: [:create]
      resources :posts, only: [:update, :destroy, :show]
    end
  end

end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :body, length: { minimum: 5 }, presence: true
  validates :user, presence: true

  # number 1,3 in checkpoint, oldest->newest / top->bottom
  default_scope { order('updated_at ASC')}

  after_create :send_favorite_emails


  private

  def send_favorite_emails
    post.favorites.each do |favorite|
      FavoriteMailer.new_comment(favorite.user, post, self).deliver_now
    end
  end

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/label.rb
class Label < ActiveRecord::Base
  has_many :labelings
  belongs_to :labelable, polymorphic: true

  has_many :topics, through: :labelings, source: :labelable, source_type: :Topic
  has_many :posts, through: :labelings, source: :labelable, source_type: :Post

  def self.update_labels(label_string)
    return Label.none if label_string.blank?

    label_string.split(",").map do |label|
      Label.find_or_create_by(name: label.strip)
    end
  end
end

app/models/labeling.rb
class Labeling < ActiveRecord::Base
  belongs_to :labelable, polymorphic: true
  belongs_to :label
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy

  has_many :labelings, as: :labelable
  has_many :labels, through: :labelings

  has_many :favorites, dependent: :destroy

  default_scope { order('rank DESC') }
  scope :visible_to, -> (user) { user ? all : joins(:topic).where('topics.public' => true) }

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :topic, presence: true
  validates :user, presence: true

  def up_votes
    votes.where(value: 1).count
    # implied self.votes >> collects the votes with value 1 into a collection and then counts them
  end

  def down_votes
    votes.where(value: -1).count
  end

  def points
    votes.sum(:value)
    # #sum is a built in ActiveRecord method. We are calling sum on the value attribute
  end

  def update_rank
    age_in_days = (created_at - Time.new(1970,1,1)) / 1.day.seconds
    new_rank = points + age_in_days
    update_attribute(:rank, new_rank)
  end


end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  has_many :ratingalings
  belongs_to :ratingable, polymorphic: true

  has_many :topics, through: :ratingalings, source: :ratingable, source_type: :Topic
  has_many :posts, through: :ratingalings, source: :ratingable, source_type: :Post

  before_save { self.severity ||= :PG }

  enum severity: [ :PG, :PG13, :R ]

  def self.update_rating(rating_string)
    r = :PG
    case rating_string
    when "0"
      r = :PG
    when "1"
      r = :PG13
    when "2"
      r = :R
    else
      r = Rating.none
    end

    Rating.find_or_create_by(severity: r)

  end
end

app/models/ratingaling.rb
class Ratingaling < ActiveRecord::Base
  belongs_to :ratingable, polymorphic: true
  belongs_to :rating
end

app/models/sponsored_post.rb
class SponsoredPost < ActiveRecord::Base
  belongs_to :topic
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :posts, dependent: :destroy

  has_many :labelings, as: :labelable
  has_many :labels, through: :labelings

  scope :privately_viewable, -> { where(public: false)}
  scope :publicly_viewable, -> { where(public: true)}
  scope :visible_to, -> (user) { user ? all : publicly_viewable }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy

  has_many :favorites, dependent: :destroy

  # inline callback.
  before_save { self.email = email.downcase }
  before_save { self.role ||= :member}

  #
  before_create :generate_auth_token

  # regex for email
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, length: { minimum: 1, maximum: 100 }, presence: true
  validates :password, presence: true, length: {minimum: 6}, if: "password_digest.nil?"
  validates :password, length: { minimum: 6 }, allow_blank: true

    validates :email,
                presence: true,
                uniqueness: { case_sensitive: false },
                length: { minimum: 3, maximum: 100 },
                format: { with: EMAIL_REGEX}

  has_secure_password

  enum role: [:member, :admin]

  def favorite_for(post)
    # returns either an array of one item if the post is a fav, or nil
    favorites.where(post_id: post.id).first
  end

  def avatar_url(size)
    gravatar_id = Digest::MD5::hexdigest(self.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end

  def generate_auth_token
    loop do
      self.auth_token = SecureRandom.base64(64)
      break unless User.find_by(auth_token: auth_token)
    end
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  after_save :update_post

  validates :value, inclusion: { in: [-1, 1], message: "%{value} is not a valid vote."}, presence: true

  private

  def update_post
    post.update_rank
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def faq
  end

end

app/helpers/labels_helper.rb
module LabelsHelper
  def labels_to_buttons(labels)
    raw labels.map { |l| link_to l.name, label_path(id: l.id), class: 'btn-xs btn-primary' }.join(' ')
  end
end

app/helpers/posts_helper.rb
module PostsHelper

  def user_is_authorized_for_post?(post)
    current_user && (current_user == post.user || current_user.admin?)
  end

  def user_is_authorized_for_editing_posts?(post)
    current_user && (current_user.admin? || current_user.moderator?)
  end
end

app/helpers/ratings_helper.rb
module RatingsHelper
  def ratings_to_buttons(ratings)
    raw ratings.map { |r| link_to r.severity, rating_path(id: r.id), class: 'btn btn-info'}.join(' ')
  end
end

app/helpers/topics_helper.rb
module TopicsHelper

  def user_is_authorized_for_topics?
    current_user && current_user.admin?
  end

  def user_is_authorized_for_editing_topics?
    #current_user && (current_user.admin? || current_user.moderator?)
    current_user.moderator?
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def any_posts?
    @user.posts.count == 0 ? false : true
  end

  def any_comments?
    @user.comments.count == 0 ? false : true
  end

  def any_posts_or_comments?
    if any_posts? || any_comments?
      true
    else
      false
    end
  end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<h1>About Bloccit</h1>
<p>Created by: Me</p>

app/views/welcome/contact.html.erb
<h1>HELLO</h1>
<h2>I AM CONTACT PAGE</h2>
<h3>Contact me here or rather on here but not &#8594;here&#8592; precisely</h3>
<h4>Use my contact information to contact me</h4>
<h5>No harm in reaching out using this information</h5>
<h6><a href="mailto:russellmschmidt@gmail.com">My email</a></h6>
<p>This is my email. Or rather that was my email.</p>

app/views/welcome/faq.html.haml
.container
  %h1 F.A.Q.
  .container-md-12.row
    %p.row
      %dl
        %dt.question What is best in life?
        %dd.answer To crush your enemies, to see them driven before you, and to hear the lamentation of their women
        %dt.question What is inscribed on Conan's sword?
        %dd.answer Suffer no guilt, ye who wield this in the name of Crom.
        %dt.question What historical god is Crom based off of?
        %dd.answer The Irish Celtic god Crom Cruach, who demanded human sacrifice.

      %h4.col-md-12.row Important People in History
      - characters = %W{Conan Thulsa\ Doom King\ Osric Valeria Rexor Subotai Thorgrim}
      .col-md-4
        %ul.row
          - characters.each do |c|
            %li=c

      .col-md-8
        %img.row#conan{:src => "http://i.kinja-img.com/gawker-media/image/upload/yvqylz3c0ywhkpt1g8of.jpg", :alt => "Conan"}

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1>Bloccit</h1>
  <p>
    <%= link_to "Sign in", new_session_path, class: "btn btn-primary" %> or
    <%= link_to "Sign up!", new_user_path, class:"btn btn-primary" %>
  </p>
</div>

<div class="row">
  <div class="col-md-4">
    <h2>Solves world hunger</h2>
    <p>
      Bloccit will deliver food and water to those in need, all over the world.
    </p>
  </div>
  <div class="col-md-4">
    <h2>Eliminates poverty</h2>
    <p>
      Bloccit will deliver money and education to those in need, all over the world.
    </p>
  </div>
  <div class="col-md-4">
    <h2>Makes you better looking</h2>
    <p>
      Bloccit will make you better looking; it's scientifically proven to make men look like Ryan Gosling and women look like Shakira.
    </p>
  </div>

</div>