config/routes.rb
Rails.application.routes.draw do

  resources :labels, only: [:show]

  resources :advertisements, only: [:index, :show, :new, :create]
  resources :questions
  resources :topics do
    resources :posts, except: [:index]
  end

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
    resources :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]

  resources :welcome, only: [] do
    collection do
      get 'about'
      get 'contact'
      get 'faq'
    end
  end

  root to: 'welcome#index'

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show, :create, :update]
      resources :topics, except: [:edit, :new]
        resources :posts, only: [:create]
      resources :posts, only: [:update, :destroy, :show]
    end
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy

  has_many :labelings, as: :labelable
  has_many :labels, through: :labelings

  has_many :favorites, dependent: :destroy

  default_scope { order('rank DESC') }
  scope :visible_to, -> (user) { user ? all : joins(:topic).where('topics.public' => true) }

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :topic, presence: true
  validates :user, presence: true

  def up_votes
    votes.where(value: 1).count
    # implied self.votes >> collects the votes with value 1 into a collection and then counts them
  end

  def down_votes
    votes.where(value: -1).count
  end

  def points
    votes.sum(:value)
    # #sum is a built in ActiveRecord method. We are calling sum on the value attribute
  end

  def update_rank
    age_in_days = (created_at - Time.new(1970,1,1)) / 1.day.seconds
    new_rank = points + age_in_days
    update_attribute(:rank, new_rank)
  end


end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::V1::BaseController
  before_filter :authenticate_user, only: [:create, :update, :destroy]

  def update
    post = Post.find(params[:id])

    if post.update_attributes(post_params)
      render json: post.to_json, status: 200
    else
      render json: {error: "Post update failed", status: 400}, status: 400
    end
  end


  def destroy
    post = Post.find(params[:id])
    if post.destroy
      render json: {message: "Post destroyed", status: 200}, status: 200
    else
      render json: {error: "Post destroy failed", status: 400}, status: 400
    end
  end


  def create
    topic = Topic.find(params[:post][:topic_id])
    post = topic.posts.build(post_params)
    post.user = @current_user

    if post.valid?
      post.save!
      render json: post.to_json, status: 201
    else
      render json: {error: "Post is invalid", status: 401}, status: 401
    end
  end

  def show
    post = Post.find(params[:id])
    if post.valid?
      render json: post.to_json(include: [:comments, :votes, :favorites]), status: 200
    else
      render json: {error: "Post not found", status: 404}, status: 404
    end
  end


  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
## Make sure this is 1st up
  before_action :require_sign_in, except: :show
  before_action :authorize_user, except: [:show, :new, :create]

## all actions after this
  def show
    @post = Post.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = @topic.posts.build(post_params)
    @post.user = current_user

    if @post.save
      @post.labels = Label.update_labels(params[:post][:labels])
      @post.rating = Rating.update_rating(params[:post][:rating])
      flash[:notice] = "Post was saved"
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.assign_attributes(post_params)

    if @post.save
      @post.labels = Label.update_labels(params[:post][:labels])
      @post.rating = Rating.update_rating(params[:post][:rating])
      flash[:notice] = "Post was updated"
      redirect_to [@post.topic, @post]
    else
      flash[:error] = "There was an error saving your update. Try again."
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])

    if @post.destroy
      flash[:notice] = "\"#{@post.title}\" was deleted successfully."
      redirect_to @post.topic
    else
      flash[:error] = "There was an error deleting the post"
      render :show
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def authorize_user
    post = Post.find(params[:id])
    unless current_user == post.user || current_user.admin?
      flash[:error] = "You must be an admin to do that"
      redirect_to [post.topic, post]
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper

  def user_is_authorized_for_post?(post)
    current_user && (current_user == post.user || current_user.admin?)
  end

  def user_is_authorized_for_editing_posts?(post)
    current_user && (current_user.admin? || current_user.moderator?)
  end
end

app/views/posts/_form.haml
=form_for [topic, post] do |f|
  - if post.errors.any?
    .alert.alert-danger
      %h4=pluralize(post.errors.count, "error")
      %ul
        - post.errors.full_messages.each do |msg|
          %li=msg
  = form_group_tag(post.errors[:title]) do
    =f.label :title
    =f.text_field :title, class: 'form-control', placeholder: 'Enter a title'
  = form_group_tag(post.errors[:body]) do
    =f.label :body
    =f.text_area :body, rows: 8, class: 'form-control', placeholder: 'Enter post here'
  .form_group=render partial: 'labels/form', locals: { f: f, topic: @topic, labels: @post.labels }
  .form_group=render partial: 'ratings/form', locals: { f: f, topic: @topic, rating: @post.rating }
  .form-group
    =f.submit "Save", class: "btn btn-success"

app/views/posts/_post.haml
.media
  = render partial: 'votes/voter', locals: { post: post }
  .media-body
    %h4.media-heading
      = link_to post.title, topic_post_path(post.topic, post)
      = render partial: "labels/list", locals: {labels: post.labels}
    %small
      submitted
      = time_ago_in_words(post.created_at)
      ago by
      = post.user.name
      = post.comments.count
      Comments

app/views/posts/_post.html.erb
<div>
  <h1><%= post.title %>
    <small><%=time_ago_in_words(post.created_at)%> ago by <%=post.user.name%></small>
  </h1>
  <p>
    <%= post.body %>
  </p>

</div>

app/views/posts/edit.html.haml
.container
  %h1.row Edit Post
  .row
    .col-md-4
      %h4 Guidelines for Posts
      %ul
        %li Make it rhyme
        %li Make it a haiku
        %li Use lots of hashbrowns
    .col-md-8
      = render partial: 'form', locals: { topic: @post.topic, post: @post }

app/views/posts/new.html.haml
.container
  %h1.col-sm-12 New Post
  = render partial: 'form', locals: {topic: @topic, post: @post}

app/views/posts/show.html.haml
.container
  .row
    = render partial: 'votes/voter', locals: { post: @post }
    %h1
      =@post.title
      %small submitted #{time_ago_in_words(@post.created_at)} ago by #{@post.user.name}
  .row
    .col-md-8
      = render partial: "labels/list", locals: {labels: @post.labels }
      %br/
      %br/
  .row
    .col-md-8
      %p=@post.body
      %div
        %h3 Comments
        .js-comments
          = render @post.comments
      - if current_user
        .new-comment
          = render 'comments/form', comment: Comment.new, post: @post
    - if user_is_authorized_for_post?(@post)
      .col-md-4
        =link_to "Edit", edit_topic_post_path(@post.topic, @post), class: "btn btn-success"
        =link_to "Delete Post", [@post.topic, @post], method: :delete, class: "btn btn-danger", data: {confirm: "R U Sure? Delete is forever"}
    .col-md-4
      %h3
        =pluralize(@post.points, 'point')
        .votes
          %small
            =pluralize(@post.up_votes, 'up vote')
            &amp;
            =pluralize(@post.down_votes, 'down vote')
      - if current_user
        = render partial: "favorites/favorite", locals: {post: @post}